name: 01 - Building Blocks

on: workflow_dispatch

jobs: 
    echo-hello:
        runs-on: windows-latest
        steps:
            - name: Say Hello
              run: echo "Hello, World!"
    echo-goodbye:
        runs-on: windows-latest
        steps:
            - name: Successful Step
              run: |
                echo "I will succeed"
                exit 0
            - name: Say Goodbye
              run: echo "Goodbye, World!"
