name: 09 - Using Functions

on:
        pull_request:
        workflow_dispatch:

jobs:
     echo1:
        runs-on: ubuntu-latest
        steps:
          - name: Failing step
            run: exit 1
          - name: I will be skipped
            if: ${{ success() }}
            run: echo "I will print if previous steps succeeded."
          - name: I will execute
            if: ${{ failure() }}
            run: echo "I will print if any previous step failed."
          - name: I will execute
            if: ${{ !cancelled() }}
            run: echo "I will always pring, except wht the workflow is cancelled."
          - name: I will execute when cancelled
            if: ${{ cancelled() }}
            run: echo "I will print only when the workflow is cancelled."



